# Environment settings
CUSTOM_ENV: true
SEED: 42
MAX_EPISODES: 10000
TRAIN_STEPS: 150
CHANNELS_LAST: False
DISCRETE_ACTIONS: True

# Learning parameters
ARCH: "mlp"
O_U_NOISE: False
EXPL_NOISE: 0.1
MEAN_NOISE: 0.0
THETA: 0.15
DT: 0.01
LR_ACTOR: 0.001
LR_CRITIC: 0.001
GAMMA: 0.98
MEMORY_SIZE: 200000
LEARN_STEP: 10
TAU: 0.01
BATCH_SIZE: 128

# Fear
WITH_FEAR: True
FeAR_weight: -1.0
